POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Task 1",
    "description": "Task 1 desc",
    "done": false
}

###
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Task 3",
    "description": "Task 1 desc",
    "done": false
}

###
GET http://localhost:3000/api/tasks/8

###
GET http://localhost:3000/api/tasks

###
DELETE http://localhost:3000/api/tasks/3/delete

###
PATCH  http://localhost:3000/api/tasks/3/update
Content-Type: application/json

{
    "title": "Update",
    "description": "Update",
    "done": false
}